// Deprecated Node PDF generator. Replaced by Python script.
// Original content intentionally moved to deprecated folder.

const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

const outPath = path.join(__dirname, '..', 'coverage', 'pdf-test-sample.pdf');
if (!fs.existsSync(path.dirname(outPath))) {
    fs.mkdirSync(path.dirname(outPath), { recursive: true });
}

const doc = new PDFDocument({
    info: {
        Title: 'Accessibility Test PDF',
        Author: 'Recoup CI',
        Subject: 'Testing PDF/UA via veraPDF',
        Keywords: 'test, accessibility, pdf/ua'
    },
    tagged: true,
    displayTitle: true,
});

const stream = fs.createWriteStream(outPath);
doc.pipe(stream);

doc.fontSize(20).text('Accessibility Test PDF', { align: 'center' });

doc.moveDown();

doc.fontSize(12).text('This PDF is generated by a CI script to validate PDF/UA compliance using veraPDF.');

// Add some tagged structure
for (let i = 0; i < 3; i++) {
    doc.moveDown();
    doc.fontSize(14).text(`Section ${i + 1}`);
    doc.fontSize(12).text('Sample text for section with a clear reading order.');
}

doc.end();

stream.on('finish', () => {
    console.log('Generated test PDF at', outPath);
});
