from fastapi import FastAPI, Response
from fastapi.responses import StreamingResponse
from io import BytesIO
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter

app = FastAPI(title="Recoup PDF Service")


def generate_test_pdf_bytes() -> bytes:
    """Create a simple PDF with metadata and return bytes."""
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    c.setTitle("Accessibility Test PDF")
    c.setAuthor("Recoup CI")
    c.setSubject("Testing PDF/UA via veraPDF")
    c.setFont("Helvetica-Bold", 20)
    width, height = letter
    c.drawCentredString(width / 2, height - 72, "Accessibility Test PDF")

    c.setFont("Helvetica", 12)
    c.drawString(72, height - 120, "This PDF is generated by a CI script to validate PDF/UA compliance using veraPDF.")

    y = height - 160
    for i in range(1, 4):
        c.setFont("Helvetica-Bold", 14)
        c.drawString(72, y, f"Section {i}")
        y -= 20
        c.setFont("Helvetica", 12)
        c.drawString(72, y, "Sample text for section with a clear reading order.")
        y -= 40

    c.showPage()
    c.save()
    buffer.seek(0)
    return buffer.read()


@app.get("/generate/test-pdf")
async def generate_test_pdf():
    """HTTP endpoint for generating a sample PDF used in CI and local validation."""
    pdf_bytes = generate_test_pdf_bytes()
    return Response(content=pdf_bytes, media_type="application/pdf")


@app.get("/health")
async def health():
    return {"status": "ok"}
