#!/usr/bin/env python3
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from io import BytesIO
import os

OUT_PATH = os.path.join(os.path.dirname(__file__), '..', 'coverage', 'pdf-test-sample.pdf')

def generate_test_pdf_bytes():
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    c.setTitle('Accessibility Test PDF')
    c.setAuthor('Recoup CI')
    c.setSubject('Testing PDF/UA via veraPDF')
    c.setFont('Helvetica-Bold', 20)
    width, height = letter
    c.drawCentredString(width / 2, height - 72, 'Accessibility Test PDF')

    c.setFont('Helvetica', 12)
    c.drawString(72, height - 120, 'This PDF is generated by a CI script to validate PDF/UA compliance using veraPDF.')

    y = height - 160
    for i in range(1, 4):
        c.setFont('Helvetica-Bold', 14)
        c.drawString(72, y, f'Section {i}')
        y -= 20
        c.setFont('Helvetica', 12)
        c.drawString(72, y, 'Sample text for section with a clear reading order.')
        y -= 40

    c.showPage()
    c.save()
    buffer.seek(0)
    return buffer.read()


def main():
    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, 'wb') as f:
        f.write(generate_test_pdf_bytes())
    print('Generated test PDF at', OUT_PATH)

if __name__ == '__main__':
    main()
